### ISSUE TITLE
Ultra-lightweight DOM implementation for server rendering

### ISSUE THREAD

**Issue by daliwali** [daliwali/simulacra#48]
While [`domino`](https://github.com/fgnass/domino) is a comprehensive solution to running DOM in Node.js, Simulacra.js uses only a subset of the DOM API. Essentially all it needs to do is build a string and support only the DOM API that Simulacra.js uses.

Strawman:

``` js
const simulacra = require('simulacra')

// DOM subset used by Simulacra.js
const DOM = require('simulacra/dom')

const bindObject = (data, binding, node) =>
  simulacra.call(DOM, data, binding, node)
```

Or maybe even better:

``` js
// Use built-in DOM implementation.
// Return value is a string instead of DOM Node.
const renderHTML = require('simulacra/render')

const output = renderHTML(data, binding, templateString)
```

**Comment by 0x8890** [comment]
This is actually probably not worth doing, `domino` should already be fast enough and with this approach, not everything that can be done in a browser could be done in the server.

**Comment by 0x8890** [comment]
Actually this is worth looking into, since building the documentation page for this project takes about 30 ms, it could be much faster.

**Comment by 0x8890** [comment]
Nevermind, it seems that the bottleneck for building the docs was just parsing the whole HTML output from the Readme file, which could probably be done more efficiently anyways. Without that part, it was reasonably fast, ~10ms.

**Comment by sapeien** [comment]
Could still be faster.

**Comment by daliwali** [comment]
Done https://github.com/daliwali/simulacra/commit/9d980b6ad76fb01b938f0b7a5a7042952837cdec
