### ISSUE TITLE
Home site simulacra.js.org does not work in IE11

### ISSUE THREAD

**Issue by hardhub** [daliwali/simulacra#55]
Is it lack of support even for IE11?

**Comment by daliwali** [comment]
It should be able to support IE9+. I'll investigate if it's a problem in the library itself, or in the example.

**Comment by daliwali** [comment]
Turns out that the feature detection was implemented incorrectly, it complains that `Node.prototype.contains` doesn't exist in IE, but it works since IE5. This can be fixed.

**Comment by daliwali** [comment]
fixed https://github.com/daliwali/simulacra/commit/bbb3724a043c564cc5cd3ca4f8598429153c4ccc
