### ISSUE TITLE
Question: detect mount of the whole component

### ISSUE THREAD

**Issue by pavel** [daliwali/simulacra#57]
Having the following code:
```js
function createComponent(template) {
  var state = {
    name: ''
  };
  return simulacra(state, [ template, {
    name: '.name'
  } ]);
}
```

Is there a way to detect mount of a component returned from `createComponent` function within `createComponent` function?

**Comment by daliwali** [comment]
You mean, when the DOM element is inserted into the document? There's the native `MutationObserver` for that. I'm not sure I understand what you are trying to do.

**Comment by pavel** [comment]
In the previous code in the function `createComponent` I want to know when the component is initiated for the first time so I can animate (for example) the whole thing.

**Comment by daliwali** [comment]
If you want to animate something when it is inserted into the DOM, it's not trivial, even when you just do it with vanilla JS. Take a look at how it's done with the `animate` helper: https://github.com/daliwali/simulacra/blob/bbb3724a043c564cc5cd3ca4f8598429153c4ccc/lib/helpers.js#L72

If you want to handle animations when inserting root elements to the document, that's outside of the scope of this library. But animations for bound elements are handled by this library: http://simulacra.js.org/#helper-functions

**Comment by pavel** [comment]
I undestand. Also is there a way to attach event handler without specifying data (e.g. for a button)?

**Comment by daliwali** [comment]
Sure, you can define something like:

```js
[ 'selector', { ... }, function (element) {
  element.querySelector('button').addEventListener('click', function (event) {
    // Do whatever with the click event
    event.preventDefault()
  })
} ]
```

If your app doesn't need any sort of localization then the above works fine. But generally for a locale-aware app, every string needs to be translated, including buttons, so you'd have the button text as part of the state anyways. It wouldn't make much sense to hard-code strings in the HTML template in that case.

**Comment by pavel** [comment]
Does it mean that even if I don't need local-aware behavior I'll still need to have a placeholder in my state, e.g.:
```js
var state = {
  btn: ''
};
var definition = {
  btn: ['.btn', btnChangeFn]
};
```
?

**Comment by daliwali** [comment]
No, the code I posted above is an example of how to attach events to child elements without state.

**Comment by pavel** [comment]
I don't get it.
Let me give you an example, so you could lead me into the right direction:
```html
<template id="component">
  <input class="user">
  <input class="pwd" type="password">
  <button class="btn">Login</button>
</template
```
```js
// MyComponent.js
exports.create = function (template) {
  var state = {
    user: '',
    pwd: '',
  };

  function userChanged() {
    // ...
  }

  function pwdChanged() {
    // ...
  }

  var definition = {
    user: [ '.user', userChanged ],
    pwd: [ '.pwd', pwdChanged ]
  };

  return simulacra(state, [ template, definition ]);
}
```

Now how do I add just an event listener for a button?

**Comment by daliwali** [comment]
In this case you're trying to attach an event listener on the root element. Anything involving the root element is outside the scope of this library, since it doesn't know anything about where the root element is or whether it's inserted or not. Once you get a root element, that's where this library ends.

You could handle it like so:

```js
var rootElement = simulacra(...)

rootElement.querySelector('button').addEventListener('click', function (event) {
  ...
})

return rootElement
```

**Comment by pavel** [comment]
Cool. One more, I promise :) Can you have multiple `state` variables work with a single selector?
For example:
```js
// MyComponent.js
exports.create = function (template) {
  var state = {
    user: '',
    pwd: '',
    userIsKnow: false
  };

  function userChanged() {
    // ...
  }

  function pwdChanged() {
    // ...
  }

  function userIsKnownChanged() {
    // ...
  }

  var definition = {
    user: [ '.user', userChanged ],
    userIsKnow: [ '.user', userIsKnownChanged ],
    pwd: [ '.pwd', pwdChanged ]
  };

  return simulacra(state, [ template, definition ]);
}
```

**Comment by daliwali** [comment]
It shouldn't :) There is a safety check for a similar case, but it should also check if a selector matches the same element: https://github.com/daliwali/simulacra/blob/bbb3724a043c564cc5cd3ca4f8598429153c4ccc/lib/index.js#L205-L215

In your case, just omit the selector for `userIsKnow`. The element will be the root element in that case.

**Comment by pavel** [comment]
Omitting the selector does not seem to work.
With any of the following definitions:
```js
var definition = {
  user: [ '.user', userChanged ],
  userIsKnow: [ userIsKnownChanged ],
  pwd: [ '.pwd', pwdChanged ]
};
```
```js
var definition = {
  user: [ '.user', userChanged ],
  userIsKnow: userIsKnownChanged,
  pwd: [ '.pwd', pwdChanged ]
};
```

I get an error:
```
Uncaught TypeError: The first position on key "userIsKnow" must be
a DOM element or a CSS selector string.
```

**Comment by daliwali** [comment]
The latter is correct, it should be a function:

```js
var definition = {
  userIsKnow: function (element, value) { ... }
}
```

**Comment by pavel** [comment]
It fails with the error:
```
Uncaught TypeError: The first position on key "userIsKnown" must be
a DOM element or a CSS selector string.
```

See [this example](http://jsbin.com/zacoweqinu/edit?html,js,output).

**Comment by daliwali** [comment]
OK, I see what the problem is now.

**Short answer**: use a `div` instead of a `template`.

Long answer is that these two element types behave drastically different behind the scenes. The example given on the readme and homepage imply that you should use a template. This works in almost all cases except when you need to deal with the node of the template. The template's content doesn't belong to an `Element` but rather a `DocumentFragment`. This node actually doesn't exist in serialized HTML but is used to insert nodes with a single operation. It does not have an element, it's just a lightweight container of nodes.

**Comment by daliwali** [comment]
By the way, your toy example needs to expose the `state` object, otherwise nothing can read or update it. It is hidden inside of a closure.

**Comment by pavel** [comment]
Got it. Thank you.
