### ISSUE TITLE
Why does order of the bindings matter?

### ISSUE THREAD

**Issue by PierBover** [daliwali/simulacra#67]
For this template:
```html
<div class="news">
  <div class="image"></div>
  <h3></h3>
  <p></p>
</div>
```
This binding produces the expected iterated list of news:
```js
news: ['.news', {
  img: '.image',
  title: 'h3',
  excerpt: 'p'
}]
```
![image](https://user-images.githubusercontent.com/226483/47607983-ead2e880-d9ec-11e8-9cef-080faf262dc5.png)

But when changing the order of the bindings to this:
```js
news: ['.news', {
  title: 'h3',
  excerpt: 'p',
  img: '.image'
}]
```
I get this:

![image](https://user-images.githubusercontent.com/226483/47607995-0c33d480-d9ed-11e8-81dc-5f268e99a141.png)

It seems weird that the binding would be so tightly coupled to the DOM structure.

**Comment by daliwali** [comment]
This is most likely a bug, but I can explain why. Iterating over keys of JS objects is ordered by when the key was assigned, from first to last. When this order doesn't match the order in the DOM, the "marker" nodes get placed in the wrong places.

An obvious and easy workaround would be to order the keys by it's order in the DOM (which is what I'm doing currently), but you're right, this shouldn't be necessary. I will get around to fixing this.

**Comment by PierBover** [comment]
Thanks for your fast response.

Simulacra is great btw. I'm eagerly waiting for the new version of Riot.

**Comment by daliwali** [comment]
This has been fixed in https://github.com/daliwali/simulacra/commit/8ea82dcade60013ebbf7574e90bb30a409dfdc68

There is this example here: https://github.com/daliwali/simulacra/blob/master/test/demo.html
